/**
 * Temporary sector map for top NSE stocks.
 * This can be expanded later or replaced by a better reference source.
 */
export const STOCK_SECTOR_MAP: Record<string, string> = {
  RELIANCE: "Energy",
  HDFCBANK: "Banking",
  ICICIBANK: "Banking",
  SBIN: "Banking",
  AXISBANK: "Banking",
  KOTAKBANK: "Banking",
  INDUSINDBK: "Banking",
  BANKBARODA: "Banking",
  PNB: "Banking",
  UNIONBANK: "Banking",
  CANBK: "Banking",
  BANKINDIA: "Banking",
  INDIANB: "Banking",
  FEDERALBNK: "Banking",
  AUBANK: "Banking",
  SBICARD: "Financial Services",
  BAJFINANCE: "Financial Services",
  BAJAJFINSV: "Financial Services",
  BAJAJHLDNG: "Financial Services",
  JIOFIN: "Financial Services",
  PFC: "Financial Services",
  RECLTD: "Financial Services",
  CHOLAFIN: "Financial Services",
  SHRIRAMFIN: "Financial Services",
  LTF: "Financial Services",
  MFSL: "Financial Services",
  ABCAPITAL: "Financial Services",
  TCS: "Information Technology",
  INFY: "Information Technology",
  HCLTECH: "Information Technology",
  WIPRO: "Information Technology",
  TECHM: "Information Technology",
  LTIM: "Information Technology",
  LTIMINDTREE: "Information Technology",
  MPHASIS: "Information Technology",
  PERSISTENT: "Information Technology",
  OFSS: "Information Technology",
  COFORGE: "Information Technology",
  NAUKRI: "Internet Services",
  PAYTM: "Internet Services",
  POLICYBZR: "Internet Services",
  SWIGGY: "Internet Services",
  NYKAA: "Internet Services",
  BHARTIARTL: "Telecom",
  INDUSTOWER: "Telecom",
  IDEA: "Telecom",
  TATACONSUM: "Consumer Goods",
  HINDUNILVR: "Consumer Goods",
  NESTLEIND: "Consumer Goods",
  GODREJCP: "Consumer Goods",
  BRITANNIA: "Consumer Goods",
  DABUR: "Consumer Goods",
  PATANJALI: "Consumer Goods",
  MARICO: "Consumer Goods",
  RADICO: "Consumer Goods",
  UNITDSPR: "Consumer Goods",
  VBL: "Consumer Goods",
  TATAMOTORS: "Automobile",
  TMCV: "Automobile",
  TMPV: "Automobile",
  MARUTI: "Automobile",
  BAJAJ_AUTO: "Automobile",
  "BAJAJ-AUTO": "Automobile",
  HEROMOTOCO: "Automobile",
  EICHERMOT: "Automobile",
  TVSMOTOR: "Automobile",
  MOTHERSON: "Automobile Components",
  SAMVARDHANA: "Automobile Components",
  EXIDEIND: "Automobile Components",
  MRF: "Automobile Components",
  APOLLOHOSP: "Healthcare",
  MAXHEALTH: "Healthcare",
  FORTIS: "Healthcare",
  SUNPHARMA: "Pharmaceuticals",
  DRREDDY: "Pharmaceuticals",
  CIPLA: "Pharmaceuticals",
  DIVISLAB: "Pharmaceuticals",
  ZYDUSLIFE: "Pharmaceuticals",
  TORNTPHARM: "Pharmaceuticals",
  ALKEM: "Pharmaceuticals",
  LAURUSLABS: "Pharmaceuticals",
  MANKIND: "Pharmaceuticals",
  BIOCON: "Pharmaceuticals",
  LUPIN: "Pharmaceuticals",
  HDFCLIFE: "Insurance",
  SBILIFE: "Insurance",
  ICICIPRULI: "Insurance",
  ICICIGI: "Insurance",
  LT: "Engineering & Construction",
  LTM: "Engineering & Construction",
  SIEMENS: "Capital Goods",
  ENRIN: "Capital Goods",
  ABB: "Capital Goods",
  CUMMINSIND: "Capital Goods",
  HAVELLS: "Electrical Equipment",
  KEI: "Electrical Equipment",
  DIXON: "Electronics Manufacturing",
  BEL: "Defence Electronics",
  HAL: "Defence & Aerospace",
  BDL: "Defence",
  COCHINSHIP: "Shipbuilding",
  RVNL: "Railways",
  IRCTC: "Railways",
  IRFC: "Railways",
  POWERGRID: "Power",
  NTPC: "Power",
  NHPC: "Power",
  TATAPOWER: "Power",
  ADANIPOWER: "Power",
  ADANIENSOL: "Power",
  ADANIGREEN: "Power",
  JSWENERGY: "Power",
  OIL: "Oil & Gas",
  ONGC: "Oil & Gas",
  IOC: "Oil & Gas",
  HINDPETRO: "Oil & Gas",
  COALINDIA: "Mining",
  VEDL: "Mining & Metals",
  NMDC: "Mining & Metals",
  NATIONALUM: "Metals",
  HINDALCO: "Metals",
  HINDZINC: "Metals",
  JINDALSTEL: "Metals",
  JSWSTEEL: "Metals",
  TATASTEEL: "Metals",
  GRASIM: "Materials",
  PIDILITIND: "Chemicals",
  ASTRAL: "Chemicals",
  COROMANDEL: "Chemicals",
  SRF: "Chemicals",
  PIIND: "Chemicals",
  ASIANPAINT: "Paints",
  SHREECEM: "Cement",
  AMBUJACEM: "Cement",
  ULTRACEMCO: "Cement",
  DLF: "Real Estate",
  LODHA: "Real Estate",
  OBEROIRLTY: "Real Estate",
  GODREJPROP: "Real Estate",
  PRESTIGE: "Real Estate",
  PHOENIXLTD: "Real Estate",
  DMART: "Retail",
  TRENT: "Retail",
  VMM: "Retail",
  INDIGO: "Aviation",
  GMR: "Airports",
  GMRAIRPORT: "Airports",
  ADANIPORTS: "Ports & Logistics",
  CONCOR: "Logistics",
  MUTHOOTFIN: "Financial Services",
  BOSCHLTD: "Automobile Components",
  PAGEIND: "Consumer Discretionary",
  TITAN: "Consumer Discretionary",
  JUBLFOOD: "Consumer Discretionary",
  INDIHOTEL: "Hospitality",
  INDHOTEL: "Hospitality",
  VOLTAS: "Consumer Durables",
  TIINDIA: "Industrial Products",
  APLAPOLLO: "Industrial Products",
  MCX: "Exchange",
  BSE: "Exchange",
  HUDCO: "Housing Finance",
  LICHSGFIN: "Housing Finance",
};